title: M10PROG - Laravel
description: "M10PROG - Werken voor opdrachtgevers"
email: j.heidebrink@ma-web.nl

github_username:  jheidebrink-ma

# Build settings
baseurl: "/M10PROG-Site"
remote_theme: "pmarsceill/just-the-docs"

#plugins:
#  - jekyll-feed

exclude: ["code-examples", "start.sh", ".idea", "sketch"]
search_enabled: false
heading_anchors: false

# Config theme
# See: https://pmarsceill.github.io/just-the-docs/docs/configuration/
# color_scheme: dark

logo: "/assets/images/logo.png"

#bap:
#  assignment_url: https://classroom.github.com/a/a3oV1MzV
#  skip_date_check: false
